version: 2
plugins:
  duplication:
    enabled: false
  tslint:
    config: tsconfig.json
    enabled: true
exclude_patterns:
  - 'gulpfile.js'
  - 'src/bench.ts'
  - 'src/*.spec.ts'
  - 'src/*.bench.ts'
  - 'dist/'
  - 'examples/'
  - 'benchmarks/'
  - 'docs/'
