version: 2
plugins:
  tslint:
    config: tsconfig.json
    enabled: true
exclude_patterns:
  - "src/bench.ts"
  - "src/*.spec.ts"
  - "src/*.bench.ts"
  - "dist/"
  - "examples/"
  - "benchmarks/"
  - "docs/"
